version: '3.8'

services:
  n8n-python:
    image: naskio/n8n-python:latest-debian # use this if intended to use heavy python packages
    #    image: naskio/n8n-python # alpine for light python packages
    #    command: /bin/sh -c "n8n start"
    restart: always
    container_name: n8n-python-new
    environment:
      GENERIC_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./local-files:/data/files # by default workdir == /data
      - ./python_scripts:/data/py_scripts
      - ./requirements.txt:/data/requirements.txt